name: Trigger CI Tasks 
on:
  workflow_call:
    inputs:
      EVENT:
        required: true
        type: string         
jobs:
  TriggerBuild:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2         
      - name: Dump JSON to File
        run: echo "${{ inputs.EVENT }}}" > event.json
        
#       - name: TriggerBuild with Event
#         run: |-
#               curl --location --request POST  'https://api-gw.dart.intel.com:32462/eventpublisher/api/publish'  \
#                       --header 'Content-Type: application/json' \
#                       --header 'x-github-event: abcedf' \
#                       --data-urlencode '${{ inputs.EVENT }}'

      
              
              
