name: Trigger CI Tasks 
on:
  pull_request:
    types: "**"
    branches: "**"

jobs:
  TriggerBuild:
    runs-on: test
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"


      
              
              
