name: Trigger all workflows
on:
  workflow_call:
    inputs:
      PR_EVENT:
        required: true
        type: string
      PR_URL:
        required: true
        type: string
      PR_LABEL:
        required: true
        type: string
        
      CHECKAPPROVALTOKEN:
        default: checkapproval
        required: false
        type: string
      CHECKBUGTOKEN:
        default: checkbug
        required: false
        type: string    
      JENKINS_URL:
        default: https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=
        required: false
        type: string   
permissions: read-all
jobs:
  CheckBug:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo vars
        run: 
            echo The PR_EVENT is ${{ inputs.PR_EVENT }}
            echo The PR_URL is ${{ inputs.PR_URL }}
            echo The TOKEN is ${{ inputs.PR_LABEL }}
            
      - name: Trigger Jenkins Build with PR Information
        run: |-
              curl --location --request POST  ${{ inputs.JENKINS_URL }}${{ inputs.CHECKBUGTOKEN }}   \
                      --header 'Content-Type: application/json' \
                      --data-raw '{
                        "action": ${{ inputs.PR_EVENT }} ,
                        "pull_request": {
                          "html_url": ${{ inputs.PR_URL }}
                        }
                      }'
  CheckApproval:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo vars
        run: 
            echo The PR_EVENT is ${{ inputs.PR_EVENT }}
            echo The PR_URL is ${{ inputs.PR_URL }}
            echo The LABEL is ${{ inputs.PR_LABEL }}
            
      - name: Trigger Jenkins Build with PR Information if label is Valid commit message
        if: ${{ inputs.PR_LABEL == 'Valid commit message' }} 
        run: |- 

               curl --location --request POST  ${{ inputs.JENKINS_URL }}${{ inputs.CHECKAPPROVALTOKEN }}   \
                      --header 'Content-Type: application/json' \
                      --data-raw '{
                        "action": ${{ inputs.PR_EVENT }} ,
                        "pull_request": {
                          "html_url": ${{ inputs.PR_URL }}
                        },
                        "label": {
                          "name": ${{ inputs.PR_LABEL }}
                        }                        
                      }'
                      
      - name: Trigger Jenkins Build with PR Information if label is None
        if: ${{ inputs.PR_LABEL != 'Valid commit message' }} 
        run: |- 
               curl --location --request POST  ${{ inputs.JENKINS_URL }}${{ inputs.CHECKAPPROVALTOKEN }}   \
                      --header 'Content-Type: application/json' \
                      --data-raw '{
                        "action": ${{ inputs.PR_EVENT }} ,
                        "pull_request": {
                          "html_url": ${{ inputs.PR_URL }}
                        }                     
                      }'
              

      
              
              
