name: Trigger all workflows
on:
  workflow_call:
    inputs:
      PR_EVENT:
        required: true
        type: string
      PR_URL:
        required: true
        type: string
      PR_LABEL:
        required: true
        type: string    
      EVENT:
        required: true
        type: string         
jobs:
  TriggerBuild:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2            
      - name: TriggerBuild with Event
        run: |-
              curl --location --request POST  'http://android-ci.iglb.intel.com:32462/eventpublisher/api/publish'  \
                      --header 'Content-Type: application/json' \
                      --header 'x-github-event: abcedf' \
                      --data-raw '${{ inputs.EVENT }}'

      
              
              
