name: Trigger CI Tasks 
permissions: read-all
on:
  workflow_call:
    inputs:
      EVENT:
        required: true
        type: string         
jobs:
  TriggerBuild:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2            
      - name: TriggerBuild with Event
        run: |-
              curl --location --request POST  'https://ci-events.dart.intel.com:32462/eventpublisher/api/publish'  \
                      --header 'Content-Type: application/json' \
                      --header 'x-github-event: abcedf' \
                      --data "@${{ github.event_path }}" 

      
              
              
