name: Trigger CI Tasks 
on:
  pull_request:
    types: "**"
    branches: "**"
  pull_request_review:
    types: "**"
    branches: "**"

jobs:
  TriggerBuild:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 
    - name: Dump GitHub context
      env:
        Event: ${{ github.event.action }}
      run: |
        echo "$Event"      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        exit -1


      
              
              
