name: Trigger all workflows
on:
  workflow_call:
    inputs:
      PR_EVENT:
        required: true
        type: string
      PR_URL:
        required: true
        type: string
      PR_LABEL:
        required: false
        type: string
        default: Test
        
      CHECKAPPROVALTOKEN:
        default: checkapproval
        required: false
        type: string
      CHECKBUGTOKEN:
        default: checkbug
        required: false
        type: string    
      JENKINS_URL:
        default: https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=
        required: false
        type: string   
jobs:
  CheckBug:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo vars
        run: 
            echo The PR_EVENT is ${{ inputs.PR_EVENT }}
            echo The PR_URL is ${{ inputs.PR_URL }}
            echo The TOKEN is ${{ inputs.PR_LABEL }}
            
      - name: Trigger Jenkins Build with PR Information
        run: |-
              curl --location --request POST  ${{ inputs.JENKINS_URL }}${{ inputs.CHECKBUGTOKEN }}   \
                      --header 'Content-Type: application/json' \
                      --data-raw '{
                        "action": ${{ inputs.PR_EVENT }} ,
                        "pull_request": {
                          "html_url": ${{ inputs.PR_URL }}
                        }
                      }'
  CheckApproval:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo vars
        run: 
            echo The PR_EVENT is ${{ inputs.PR_EVENT }}
            echo The PR_URL is ${{ inputs.PR_URL }}
            echo The LABEL is ${{ inputs.PR_LABEL }}           
      - name: Trigger Jenkins Build with PR Information
        run: |-
              curl --location --request POST 'https://cbjenkins-ba.devtools.intel.com/teams-satg-aee-android-ci/generic-webhook-trigger/invoke?token=checkapproval_test&action=labeled&pull_request_url=https://github.com/intel-sandbox/shahbaz-moja-public/pull/24&pr_label=Valid%20commit%20message' \
              --header 'Accept: application/vnd.github.v3+json' \
              --header 'Content-Type: application/json' \
              --data - raw '{
                  "action": "labeled",
                  "pull_request": {
                      "html_url": "https://github.com/intel-sandbox/shahbaz-moja-public/pull/24"
                  },
                  "label": {
                      "name": "Valid commit message"
                  }}'
