name: test
on:
  workflow_call:
    inputs:
      EVENT:
        required: true
        type: string         
jobs:
  TriggerBuild:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2        
      - name: List Directory Contents
        run: ls -al
#       - name: Execute Python Script
#         run: python .github/workflows/scripts/test.py


        
#       - name: TriggerBuild with Event
#         run: |-
#               curl --location --request POST  'https://api-gw.dart.intel.com:32462/eventpublisher/api/publish'  \
#                       --header 'Content-Type: application/json' \
#                       --header 'x-github-event: abcedf' \
#                       --data-urlencode '${{ inputs.EVENT }}'

      
              
              
